### ISSUE TITLE
http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98" msg=)

### ISSUE THREAD

**Issue by dgur-outbrain** [prometheus/prometheus#13678]
### What did you do?

Multiple errors of `ts=2024-02-29T16:40:47.378Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98" msg=)` in the logs - during normal operation.

### What did you expect to see?

No errors.

### System information

Linux 4.15.0-142-generic x86_64

### Prometheus version

```text
prometheus, version 2.47.2 (branch: HEAD, revision: 3f3172cde1ee37f1c7b3a5f3d9b031190509b3ad)
  build user:       root@79f2ad339b75
  build date:       20231012-16:07:10
  go version:       go1.21.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```global:
  scrape_interval: 1m
  scrape_timeout: 50s
  evaluation_interval: 1m
  external_labels:
    thanos_distinct: lalala
rule_files:
- /etc/config/recording_rules.yml
- /etc/config/alerting_rules.yml
scrape_configs:
- job_name: pushgateway-lalala
  honor_labels: true
  honor_timestamps: true
  params:
    owner:
    - an_owner
    service:
    - serviceA
  scrape_interval: 1m
  scrape_timeout: 50s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - separator: ;
    regex: (.*)
    target_label: owner
    replacement: devx
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 11
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: ^10$
    replacement: $1
    action: keep
  metric_relabel_configs:
  - source_labels: [tmp]
    separator: ;
    regex: .*
    target_label: tmp
    action: replace
  - source_labels: [instance]
    separator: ;
    regex: (.*)
    target_label: exported_instance
    replacement: $1
    action: replace
  - source_labels: [owner]
    separator: ;
    regex: (.*)
    target_label: exported_owner
    replacement: $1
    action: replace
  - source_labels: [instance]
    separator: ;
    regex: ^$
    target_label: instance
    replacement: some_replacement
    action: replace
  static_configs:
  - targets:
    - sometarget.svc.cluster.local:9091
    labels:
      owner: devx
- job_name: fed-target
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - some_metric
  scrape_interval: 1m
  scrape_timeout: 50s
  metrics_path: /federate
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 11
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: ^10$
    replacement: $1
    action: keep
  metric_relabel_configs:
  - separator: ;
    regex: ^thanos_distinct$
    replacement: $1
    action: labeldrop
  consul_sd_configs:
  - server: sometarget.svc.cluster.local:8500
    datacenter: chidc2
    tag_separator: ','
    scheme: http
    allow_stale: true
    refresh_interval: 1m
    services:
    - serviceA
    - serviceB
    follow_redirects: true
    enable_http2: true
```

### Logs

```text
ts=2024-02-29T19:48:50.391Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98" msg=)
ts=2024-02-29T19:49:15.226Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98" msg=)
ts=2024-02-29T19:49:58.233Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98" msg=)
ts=2024-02-29T20:08:02.707Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98" msg=)
```

**Comment by dgur-outbrain** [comment]
Same errors spotted with v2.50.1 as well.

**Comment by zeusal** [comment]
Same error with v2.48.0

**Comment by aknuds1** [comment]
I'm looking into this.

**Comment by aknuds1** [comment]
Could you provide a simple procedure for reproducing this log message? I've tried accessing various web server paths, and am so far unable to trigger the bug.

**Comment by dgur-outbrain** [comment]
Unfortunately now, but it seems to be happening when CPU usage is high.
I'll try to see if I can narrow it down to specific circumstances.

**Comment by aknuds1** [comment]
Thank you. From reading the code in question (wrap.go from the log message), I see they try to protect against superfluous calls to `WriteHeader`, so the bug isn't obvious.

**Comment by aknuds1** [comment]
@zeusal do you have the same experience, i.e. that it's non-trivial to reproduce?

**Comment by PrayagS** [comment]
We faced this error on `v2.53.0` as well. No anomaly spotted in the logs and memory usage was high at this point. I almost thought the pod was OOM killed but the actual reason was this error (shown up a lot of times) followed by a segmentation fault.

Logs before termination,
```
	
2024-08-13 15:56:34	
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fb68bcd0948 pc=0x284122c]
	
	
2024-08-13 15:56:34	
fatal error: fault
	
	
2024-08-13 15:56:34	
unexpected fault address 0x7fb68bcd0948


2024-08-13 15:56:27	
ts=2024-08-13T10:26:27.057Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
	
	
2024-08-13 15:56:25	
ts=2024-08-13T10:26:25.913Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
	
	
2024-08-13 15:56:25	
ts=2024-08-13T10:26:25.875Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
	
	
2024-08-13 15:56:16	
ts=2024-08-13T10:26:16.618Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
	
	
2024-08-13 15:56:11	
ts=2024-08-13T10:26:11.400Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
	
	
2024-08-13 15:56:11	
ts=2024-08-13T10:26:11.385Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
	
	
2024-08-13 15:56:11	
ts=2024-08-13T10:26:11.378Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
	
	
2024-08-13 15:56:11	
ts=2024-08-13T10:26:11.374Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
	
	
2024-08-13 15:56:11	
ts=2024-08-13T10:26:11.366Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
	
	
2024-08-13 15:56:11	
ts=2024-08-13T10:26:11.359Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
	
	
2024-08-13 15:56:11	
ts=2024-08-13T10:26:11.207Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
	
	
2024-08-13 15:56:11	
ts=2024-08-13T10:26:11.132Z caller=stdlib.go:105 level=error component=web caller="http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88" msg=)
```

**Comment by stmcginnis** [comment]
I think I may see where this is happening. I could probably write up a small repro, but I hope this description is enough to go on based on what I've seen.

Many [tutorials](https://edgedelta.com/company/blog/how-to-instrument-a-go-application-using-opentelemtry-complete-guide-best-practices) out there show instrumenting the individual route:

```go
handleFunc := func(pattern string, handlerFunc func(http.ResponseWriter, *http.Request)) {
	handler := otelhttp.WithRouteTag(pattern, http.HandlerFunc(handlerFunc))
	mux.Handle(pattern, handler)
}

handleFunc("/spinwheel", spinwheel)
```

as well as installing a server-wide handler:

```go
// Add HTTP instrumentation for the whole server
handler := otelhttp.NewHandler(mux, "/")
```

This works fine under normal operations. But if there is a problem, like possibly the side effects from high memory usage mentioned above, I see this error message. It appears when `http.Error()` is used, the first `Error()` does is write the status code in the header. But `http.Error` also takes a string to return. So in the `Error()` code, [it writes the header, then writes to the ResponseWriter](https://github.com/golang/go/blob/eb975601a07ad25a47fdcb0cc6166ec695973d3e/src/net/http/server.go#L2251-L2252).

In the `RespWriterWrapper`, I'm seeing the `writeHeader` call happen twice for this error. The first time I believe is from the direct header write from `http.Error()`, then the second one from the write of the string content.

I think there is a bug in `RespWriterWrapper`'s logic for `writeHeader()`. In the [code](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/d312469f21ca6606e872292bdca206b2680608d3/instrumentation/net/http/otelhttp/internal/request/resp_writer_wrapper.go#L76) it checks `if !w.wroteHeader`. If it hadn't written the header it will set the flag to true. But the problem here is that regardless of whether the flag is `true` or `false` it will still fall through and attempt to call `WriteHeader` at the end.

I believe this is where the original issue error message is coming from. Walking through the code execution, on the second call to `RespWriterWrapper.writeHeader()` the flag is correctly set to `true`, but it still tries to set the header anyway.

**Comment by stmcginnis** [comment]
Looks like the behavior I was seeing in the last comment is fixed in the latest release: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6055

**Comment by JonasDoe** [comment]
Starting with `v0.62.0`, the issue seem to reoccur.

**Comment by fatpat** [comment]
yes still having them on 3.7.3

what are the consequences of such logs ?

**Comment by krish7919** [comment]
> yes still having them on 3.7.3
> 
> what are the consequences of such logs ?

Storage/compute cost balloons up on our log server?

**Comment by aknuds1** [comment]
Does this problem still occur?

**Comment by aknuds1** [comment]
Closing this for now, as it might be fixed by #19749. Please let me know in case it should still not be fixed.
