### ISSUE TITLE
Web UI - Error loading available metrics!

### ISSUE THREAD

**Issue by Rohlik** [prometheus/prometheus#6535]
## Bug Report
**What did you do?**
Successfully upgraded Prometheus 2.0 to 2.15.0-rc0 and then open WEB UI.

**What did you expect to see?**
I expect /graph page without error and with working search suggest drop-down list.

**What did you see instead? Under which circumstances?**

- Open Web UI behind Apache proxy on https://prometheus.company.org/ via Google Chrome.
- I am forwarded to https://prometheus.company.org/graph page where I see "_Error loading available metrics!_" error.
- Search suggest drop-down list is **not** working, there are no suggestions.

**Environment**

* System information:

`Linux 3.10.0-1062.4.1.el7.x86_64 x86_64`

* Prometheus version:

```
prometheus, version 2.15.0-rc.0 (branch: HEAD, revision: 61f1953c50148b3857bad6ab9a5622e1f1277695)
  build user:       root@67bb57f8015b
  build date:       20191218-17:10:23
  go version:       go1.13.5
```

* Prometheus parameters:
```
/opt/prometheus/prometheus --storage.tsdb.retention.time=60d --storage.tsdb.retention.size=98GB --config.file=/opt/prometheus/prometheus.yml --storage.tsdb.path=/opt/prometheus/data --web.external-url=https://prometheus.company.org/ --web.console.templates=/opt/prometheus/consoles --query.timeout=1m --web.read-timeout=1m --web.route-prefix=/
```

**Comment by roidelapluie** [comment]
That might be related to a bug that was fixed in 2.15.1. could you check? Also, do you have the requests/response? Thanks

**Comment by Rohlik** [comment]
I upgraded Prometheus to the latest version - 2.15.1, but I still have the problem.

Request:
`Request URL: https://prometheus.monetplus.cz/api/v1/label/__name__/values?_=1577954456741
Request Method: GET
Status Code: 422 Unprocessable Entity`

Response:
`{"status":"error","errorType":"execution","error":"block: 01DRVWKQ2RT4YA8QT23G09XMNZ: get postings offset entry: invalid size"}`

**Comment by Fgruntjes** [comment]
Have got the same issue here, is there anything I can provide you with to help solve the issue?

**Comment by gbolo** [comment]
I also have the same issue. I tried rolling back to v2.14.0 but my data is still empty. I hope that it's not permanently lost... the data directory still shows a size of `150mb`

**Comment by juliusv** [comment]
@gbolo Hmm... so 2.15 introduced this? And to clarify, this is only on the old web UI on `/graph`, right? Or are you getting the same problem on `/new/graph` (the new React UI)?

It's interesting because there weren't any changes directly to the old graph UI code since 2.14 got released on Nov 11, 2019: https://github.com/prometheus/prometheus/commits/master/web/ui/static/js/graph/index.js

**Comment by roidelapluie** [comment]
Related to #6418

**Comment by juliusv** [comment]
@roidelapluie Ah thanks. I didn't see the TSDB-specific error. So not a UI problem then.

**Comment by brian-brazil** [comment]
Was the block in question created by 2.15 or an earlier version? Can you share the HTTP request, and the index file?

**Comment by juliusv** [comment]
@brian-brazil The HTTP request is in https://github.com/prometheus/prometheus/issues/6535#issuecomment-570146356, just the normal fetching of all metric names.

**Comment by Rohlik** [comment]
@juliusv I have this problem also in the new React UI, but with different error message:

> Warning: Error fetching metrics list: Unexpected response status when fetching metric names: Unprocessable Entity

HTTP request in new React UI:
```
Request URL: https://prometheus.company.org/api/v1/label/__name__/values
Request Method: GET
Status Code: 422 Unprocessable Entity
```

Response:
`{"status":"error","errorType":"execution","error":"block: 01DS1P0FNEAM2YPR8DAKCACNDJ: get postings offset entry: invalid size"}`

**Comment by juliusv** [comment]
@Rohlik Thanks!

For @brian-brazil's questions, could you share `data/01DS1P0FNEAM2YPR8DAKCACNDJ/meta.json` and `data/01DS1P0FNEAM2YPR8DAKCACNDJ/index` (careful, might contain sensitive data if your metrics are sensitive), as well as whether the time range in the block's `meta.json` file happened before or after the upgrade to 2.15?

**Comment by Rohlik** [comment]
@brian-brazil here you have what you need :)

**meta.json**:
```
{
        "version": 1,
        "ulid": "01DS1P0FNEAM2YPR8DAKCACNDJ",
        "minTime": 1572890400000,
        "maxTime": 1573084800000,
        "stats": {
                "numSamples": 343318557,
                "numSeries": 54892,
                "numChunks": 2861464
        },
        "compaction": {
                "level": 4,
                "sources": [
                        "01DRW3F8TFKRG0JYWVH908TA8Y",
                        "01DRWAB02PH017ZB9ZEQHX5X38",
                        "01DRWH6QATKYJ8S6HXP665NF25",
                        "01DRWR2EJFJM21WKM8GQ405APT",
                        "01DRWYY5TP3R2YNNQGK60JQMKQ",
                        "01DRX5SX3F62WHSYZ2NVYXC4MD",
                        "01DRXCNMABS6A4ZQ6AYXPX26PR",
                        "01DRXKHBKRZ0AXT2W3CK377R9W",
                        "01DRXTD2TCT1BVCD52RP4B337K",
                        "01DRY18T327QE2GAQH1P49V5DE",
                        "01DRY84HANDP7G549NWBB3WCFB",
                        "01DRYF08J50XH6EBC1B0RFSHRG",
                        "01DRYNVZTV50A6FJKNQE5S8QJE",
                        "01DRYWQQ2S842T024J37BYYT2G",
                        "01DRZ3KEB17CERPWRTASRN285S",
                        "01DRZAF5JN6CTBBXWR0KSTKDMG",
                        "01DRZHAWV3MSH0CE4SC1Y22QE6",
                        "01DRZR6M34CT87MYANMSBXDKVT",
                        "01DRZZ2BA5ZRVCZ00PR95BTJ9F",
                        "01DS05Y2J6QJHRBNN9P3GJCKAF",
                        "01DS0CSSTHBDGPRN32MWRWJT7Z",
                        "01DS0KNH2BZ5N828SX5EDM2XCA",
                        "01DS0TH8ACKW736WAD9SQ21K0B",
                        "01DS11CZJMK2Q35WHEC7EAFDH9",
                        "01DS188PTKE5VQ4C8XVZJCJ4RA",
                        "01DS1F4E32AAG8SDCYDDTNF7RZ",
                        "01DS1P05AFF8DPYM2XZY2XKVJV"
                ]
        }
}
```

**index** file have 27MB, so I uploaded it on GDrive - https://drive.google.com/file/d/1NXQbZqBDRqJwCPzUzgEI3BIeVUgEdUIR/view?usp=sharing

The **time range** in meta.json is related to time before upgrade to higher version.

**Comment by brian-brazil** [comment]
Okay, looks like the issue here is that the postings offset table isn't sorted - which it should be.

**Comment by brian-brazil** [comment]
So the sorting was only added in https://github.com/prometheus/tsdb/pull/216, which went into 2.1.0.

Given that noone should be using 2.0.0 for a variety of reasons (there are far worse bugs than this), I propose that we detect this at startup and error out rather than trying to deal with it gracefully. This would mean that a straight upgrade from 2.0.0 would no longer work.

**Comment by roidelapluie** [comment]
Even if you dont use 2.9 you might still have 2.0 blocks around. I would prefer some kind of repairs here.

**Comment by brian-brazil** [comment]
2.9 would have compacted them down at some point.

**Comment by gbolo** [comment]
> @gbolo Hmm... so 2.15 introduced this? And to clarify, this is only on the old web UI on `/graph`, right? Or are you getting the same problem on `/new/graph` (the new React UI)?
> 
> It's interesting because there weren't any changes directly to the old graph UI code since 2.14 got released on Nov 11, 2019: https://github.com/prometheus/prometheus/commits/master/web/ui/static/js/graph/index.js

sorry to confuse this issue with another one I had. Please ignore my comment

**Comment by Rohlik** [comment]
Thank you. After upgrade to the latest version of Prometheus is everything good.
