### ISSUE TITLE
Change `CreateBlock` to write samples directly without using `Head`

### ISSUE THREAD

**Issue by dipack95** [prometheus/prometheus#6836]
## Proposal
As mentioned in #5887, update the `CreateBlock` function to write samples directly to block, without using a `Head` appender.

I will take a crack at this, after completing #5887.

**Comment by codesome** [comment]
Thanks! I had a hacky implementation here https://github.com/codesome/tsdb/blob/0d9833190f84f61510c503489a0728415d0d97a8/db_test.go#L1833 when I was working on vertical compaction which was later removed as there was a lot of duplication of code.

With some refactoring of compaction code, it should be simpler to do it without a lot of duplication I believe.

**Comment by dipack95** [comment]
So I have already have a rough version based on the code you'd written, and the existing compaction logic, and I can already see some gains, when you have enough samples to push to disk!

Refactoring the compaction code is going to take some time, though, as I don't yet see a clear way to do so.

**Comment by dipack95** [comment]
@codesome I sporadically run into an error when using `indexw.AddSeries(ref, lset, chks...)`, complaining of an out of order series. Do you know why that might happen?

**Comment by roidelapluie** [comment]
This is fixed by #7950 @dipack95 

Can you confirm?

**Comment by codesome** [comment]
Not fixed because the new block writer uses the Head internally. But I don't think we ever faced any issue yet using the Head block, especially with m-mapping now there is not much memory requirement. So I would say this is no longer required until we face any limitations with current approach.
