### ISSUE TITLE
local error: tls: unexpected message - if ssl_stapling is activated

### ISSUE THREAD

**Issue by jloehel** [prometheus/prometheus#6858]
**What did you do?**
I am running a few exporters behind a nginx reverse proxy. I activated ssl_stapling in the nginx configuration:
```
    # OCSP Stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 valid=60s;
    resolver_timeout 2s;
```
It worked before with version 2.7.1+ds-3. I upgraded to version 2.15.2+ds. Now I am getting some tls errors. If I deactivate the ssl stapling, everything works fine.

**What did you expect to see?**
Prometheus can handle also ssl stapling

**What did you see instead? Under which circumstances?**
```
Get https://xxx:443/node-metrics: local error: tls: unexpected message
Get https://xxx:443/docker-metrics: local error: tls: unexpected message
...
```

**Environment**
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

* System information:
Linux 4.19.97-v7+ armv7l

* Prometheus version:
prometheus, version 2.15.2+ds (branch: debian/sid, revision: 2.15.2+ds-2)
  build user:       pkg-go-maintainers@lists.alioth.debian.org
  build date:       20200113-10:10:54
  go version:       go1.13.6e

* Alertmanager version:
alertmanager, version 0.15.3+ds (branch: debian/sid, revision: 0.15.3+ds-3)
  build user:       pkg-go-maintainers@lists.alioth.debian.org
  build date:       20190221-19:36:45
  go version:       go1.11.5

* Prometheus configuration file:
```
  - job_name: xxx
    static_configs:
      - targets: ['xxx']
    metrics_path: '/node-metrics'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/secrets/xxx.crt
      key_file: /etc/prometheus/secrets/xxx.key
```

* Logs:
```
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.713Z caller=main.go:328 msg="Starting Prometheus" version="(version=2.15.2+ds, branch=debian/sid, revision=2.15.2+ds-2)"
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.713Z caller=main.go:329 build_context="(go=go1.13.6, user=pkg-go-maintainers@lists.alioth.debian.org, date=20200113-10:10:54)"
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.714Z caller=main.go:330 host_details="(Linux 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l monitoring.xxx.local (none))"
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.714Z caller=main.go:331 fd_limits="(soft=16384, hard=16384)"
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.714Z caller=main.go:332 vm_limits="(soft=unlimited, hard=unlimited)"
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.722Z caller=main.go:646 msg="Starting TSDB ..."
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.722Z caller=web.go:442 component=web msg="Start listening for connections" address=0.0.0.0:9090
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.724Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1582310010280 maxt=1582311600000 ulid=01E1MJZVVXRZ244G6X39EGVMTJ
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.734Z caller=web.go:486 component=web msg="router prefix" prefix=/prometheus
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.751Z caller=head.go:584 component=tsdb msg="replaying WAL, this may take awhile"
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.881Z caller=head.go:608 component=tsdb msg="WAL checkpoint loaded"
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.885Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=2 maxSegment=6
Feb 21 20:40:04 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:04.888Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=3 maxSegment=6
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:05.176Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=4 maxSegment=6
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:05.329Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=5 maxSegment=6
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:05.330Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=6 maxSegment=6
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:05.374Z caller=main.go:661 fs_type=EXT4_SUPER_MAGIC
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:05.374Z caller=main.go:662 msg="TSDB started"
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.374Z caller=main.go:663 msg="TSDB options" MinBlockDuration=30m MaxBlockDuration=1h MaxBytes=0B UseLockfile=false RetentionDuration=2d WALSegmentSize=0B AllowOverlappingBlocks=false WALCompression=false
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:05.374Z caller=main.go:732 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.379Z caller=manager.go:222 component="discovery manager scrape" msg="Starting provider" provider=string/0 subs=[loadbalancers]
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.379Z caller=manager.go:222 component="discovery manager scrape" msg="Starting provider" provider=string/1 subs=[databases]
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.379Z caller=manager.go:222 component="discovery manager scrape" msg="Starting provider" provider=string/2 subs=[cadvisor]
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.379Z caller=manager.go:222 component="discovery manager scrape" msg="Starting provider" provider=string/3 subs=[raspberry]
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.379Z caller=manager.go:222 component="discovery manager scrape" msg="Starting provider" provider=string/4 subs=[internal]
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.380Z caller=manager.go:222 component="discovery manager scrape" msg="Starting provider" provider=string/5 subs=[external]
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.380Z caller=manager.go:222 component="discovery manager notify" msg="Starting provider" provider=string/0 subs=[config-0]
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:05.380Z caller=main.go:760 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.380Z caller=manager.go:240 component="discovery manager scrape" msg="discoverer channel closed" provider=string/4
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=info ts=2020-02-21T19:40:05.380Z caller=main.go:615 msg="Server is ready to receive web requests."
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.380Z caller=manager.go:240 component="discovery manager scrape" msg="discoverer channel closed" provider=string/1
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.380Z caller=manager.go:240 component="discovery manager scrape" msg="discoverer channel closed" provider=string/0
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.380Z caller=manager.go:240 component="discovery manager scrape" msg="discoverer channel closed" provider=string/2
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.380Z caller=manager.go:240 component="discovery manager scrape" msg="discoverer channel closed" provider=string/5
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.380Z caller=manager.go:240 component="discovery manager scrape" msg="discoverer channel closed" provider=string/3
Feb 21 20:40:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:05.380Z caller=manager.go:240 component="discovery manager notify" msg="discoverer channel closed" provider=string/0
Feb 21 20:40:10 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:10.459Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:11 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:11.149Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:12 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:12.603Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:14 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:14.828Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:16 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:16.048Z caller=scrape.go:920 component="scrape manager" scrape_pool=databases target=https://xxx/postgres-metrics msg="Scrape failed" err="Get https://xxx/postgres-metrics: local error: tls: unexpected message"
Feb 21 20:40:19 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:19.116Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:21 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:21.246Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:22 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:22.733Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:27 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:27.706Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:29 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:29.202Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:29 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:29.439Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:30 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:30.357Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:34 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:34.046Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:36 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:36.270Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:36 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:36.439Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:36 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:36.824Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:37 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:37.600Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:39 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:39.408Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:41 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:41.784Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:42 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:42.759Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:44 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:44.565Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:48 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:48.750Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:51 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:51.429Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:52 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:52.149Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:52 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:52.666Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics msg="Scrape failed" err="Get https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:56 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:56.013Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:57 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:57.222Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:57 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:57.679Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:40:58 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:58.684Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:40:59 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:40:59.923Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:00 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:00.344Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:01 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:01.507Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:03 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:03.294Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:04 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:04.823Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:05.259Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:05.597Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:05.835Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:09 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:09.216Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:10 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:10.474Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:11 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:11.168Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:12 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:12.619Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:14 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:14.830Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:16 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:16.054Z caller=scrape.go:920 component="scrape manager" scrape_pool=databases target=https://xxx/postgres-metrics msg="Scrape failed" err="Get https://xxx/postgres-metrics: local error: tls: unexpected message"
Feb 21 20:41:19 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:19.107Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:21 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:21.250Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:22 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:22.677Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:27 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:27.676Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:29 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:29.190Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:29 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:29.430Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:30 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:30.357Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:34 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:34.127Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:36 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:36.250Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:36 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:36.462Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:36 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:36.837Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:37 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:37.579Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:39 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:39.408Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:41 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:41.757Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:42 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:42.687Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:44 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:44.567Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:48 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:48.770Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:51 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:51.432Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:52 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:52.021Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:52 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:52.690Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics msg="Scrape failed" err="Get https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:55 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:55.997Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:57 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:57.231Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:57 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:57.680Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:41:58 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:58.674Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:41:59 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:41:59.841Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:00 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:00.471Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:01 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:01.490Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:03 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:03.300Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:04 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:04.819Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:05.264Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:05.580Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:05 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:05.829Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:09 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:09.216Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:10 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:10.459Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:11 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:11.148Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:12 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:12.612Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:14 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:14.819Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:16 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:16.044Z caller=scrape.go:920 component="scrape manager" scrape_pool=databases target=https://xxx/postgres-metrics msg="Scrape failed" err="Get https://xxx/postgres-metrics: local error: tls: unexpected message"
Feb 21 20:42:19 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:19.102Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:21 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:21.250Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:22 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:22.676Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:27 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:27.674Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:29 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:29.194Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:29 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:29.439Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:30 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:30.342Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:34 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:34.044Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:36 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:36.233Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:36 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:36.451Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:36 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:36.823Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:37 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:37.588Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:39 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:39.406Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:41 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:41.752Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:42 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:42.686Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
Feb 21 20:42:44 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:44.580Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:48 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:48.768Z caller=scrape.go:920 component="scrape manager" scrape_pool=external target=https://xxx/node-metrics: local error: tls: unexpected message"
Feb 21 20:42:51 monitoring.xxx.local prometheus[25967]: level=debug ts=2020-02-21T19:42:51.437Z caller=scrape.go:920 component="scrape manager" scrape_pool=cadvisor target=https://xxx/docker-metrics: local error: tls: unexpected message"
```

**Comment by brian-brazil** [comment]
You'll probably need to take this up with Debian, this is a Go bug that was fixed: https://stackoverflow.com/questions/48074154/received-unexpected-handshake-message-of-type-tls-serverkeyexchangemsg-when-wai

**Comment by jloehel** [comment]
> You'll probably need to take this up with Debian, this is a Go bug that was fixed: https://stackoverflow.com/questions/48074154/received-unexpected-handshake-message-of-type-tls-serverkeyexchangemsg-when-wai

Thanks Brian for the hint. I was not aware of that. I will close this issue.

**Comment by akshaymankar** [comment]
Hello, this is still a problem if I use the static binary for Prometheus from the latest github release.

**Comment by jloehel** [comment]
> Hello, this is still a problem if I use the static binary for Prometheus from the latest github release.

I haven't tested it for a while but actually it's not a prometheus bug. You can find the patch here: https://go-review.googlesource.com/c/go/+/86115/

**Comment by akshaymankar** [comment]
But that patch has been applied 2 years ago and the [latest prometheus build](https://github.com/prometheus/prometheus/releases/tag/v2.21.0) claims to have been built with Go 1.15. So, this shouldn't show up anymore.

**Comment by jloehel** [comment]
> But that patch has been applied 2 years ago and the [latest prometheus build](https://github.com/prometheus/prometheus/releases/tag/v2.21.0) claims to have been built with Go 1.15. So, this shouldn't show up anymore.

Sure, but I use a Debian build. It works with the official build. Because of this, I closed the bug.

**Comment by akshaymankar** [comment]
Interesting, this not working for me with the official build.

**Comment by jloehel** [comment]
> Interesting, this not working for me with the official build.

Actually, I have never tested it with the official build. I just expected that it will work. Maybe I should do it now. ^^
