### ISSUE TITLE
opening storage failed: found unsequential head chunk files 23 and 25

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7412]
**What did you do?**

Exit prometheus cleanly

```
level=warn ts=2020-06-17T18:14:44.525Z caller=main.go:524 msg="Received SIGTERM, exiting gracefully..."
level=info ts=2020-06-17T18:14:44.525Z caller=main.go:547 msg="Stopping scrape discovery manager..."
level=info ts=2020-06-17T18:14:44.525Z caller=main.go:561 msg="Stopping notify discovery manager..."
level=info ts=2020-06-17T18:14:44.525Z caller=main.go:583 msg="Stopping scrape manager..."                          
level=info ts=2020-06-17T18:14:44.525Z caller=main.go:543 msg="Scrape discovery manager stopped"                
level=info ts=2020-06-17T18:14:44.525Z caller=main.go:557 msg="Notify discovery manager stopped"                       
level=info ts=2020-06-17T18:14:44.525Z caller=manager.go:888 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-06-17T18:14:44.525Z caller=manager.go:898 component="rule manager" msg="Rule manager stopped"       
level=info ts=2020-06-17T18:14:44.525Z caller=main.go:577 msg="Scrape manager stopped"                                                
level=info ts=2020-06-17T18:14:44.531Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."               
level=info ts=2020-06-17T18:14:44.531Z caller=main.go:749 msg="Notifier manager stopped"
level=info ts=2020-06-17T18:14:44.531Z caller=main.go:761 msg="See you next time!"
```

**What did you expect to see?**

I can restart it

**What did you see instead? Under which circumstances?**

```
level=info ts=2020-06-17T18:14:51.603Z caller=main.go:302 msg="No time or size retention was set so using the default time retention" durat
ion=15d
level=info ts=2020-06-17T18:14:51.603Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.19.0, branch=master, revision=86dc8
9a39aefa5f8f64af25c22f2055137ba3423)"
level=info ts=2020-06-17T18:14:51.603Z caller=main.go:338 build_context="(go=go1.15beta1, user=roidelapluie@oxygen, date=20200617-18:00:10)
"
level=info ts=2020-06-17T18:14:51.603Z caller=main.go:339 host_details="(Linux 5.6.8-roidelapluie #1 SMP Thu Apr 30 23:23:52 CEST 2020 x86_
64 oxygen (none))"
level=info ts=2020-06-17T18:14:51.604Z caller=main.go:340 fd_limits="(soft=1024, hard=102400)"
level=info ts=2020-06-17T18:14:51.604Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-06-17T18:14:51.605Z caller=main.go:678 msg="Starting TSDB ..."
level=info ts=2020-06-17T18:14:51.605Z caller=web.go:524 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-06-17T18:14:51.605Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592352000000 maxt=1592359200000 u
lid=01EB0KB79S5NGARYRX25316A4Z
level=info ts=2020-06-17T18:14:51.605Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592373600000 maxt=1592380800000 u
lid=01EB137TZWK06KAVX4AKYV3Z1Q
level=info ts=2020-06-17T18:14:51.605Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592337196974 maxt=1592352000000 u
lid=01EB137V4XCWYST9E87QAM1NJF
level=info ts=2020-06-17T18:14:51.605Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592395200000 maxt=1592402400000 u
lid=01EB1PSKC7D1AYFMMAEHVZ39V3
level=info ts=2020-06-17T18:14:51.607Z caller=main.go:547 msg="Stopping scrape discovery manager..."
level=info ts=2020-06-17T18:14:51.607Z caller=main.go:561 msg="Stopping notify discovery manager..."
level=info ts=2020-06-17T18:14:51.607Z caller=main.go:583 msg="Stopping scrape manager..."
level=info ts=2020-06-17T18:14:51.607Z caller=main.go:557 msg="Notify discovery manager stopped"
level=info ts=2020-06-17T18:14:51.607Z caller=main.go:543 msg="Scrape discovery manager stopped"
level=info ts=2020-06-17T18:14:51.607Z caller=manager.go:888 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-06-17T18:14:51.607Z caller=manager.go:898 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-06-17T18:14:51.607Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2020-06-17T18:14:51.607Z caller=main.go:749 msg="Notifier manager stopped"
level=info ts=2020-06-17T18:14:51.607Z caller=main.go:577 msg="Scrape manager stopped"
level=error ts=2020-06-17T18:14:51.608Z caller=main.go:758 err="opening storage failed: found unsequential head chunk files 23 and 25"
```

**Environment**

* System information:

	Linux 5.6.8-roidelapluie x86_64

* Prometheus version:

  prometheus, master / 86dc89a39aefa5f8f64af25c22f2055137ba3423
  build user:       roidelapluie@oxygen
  build date:       20200617-18:00:10
  go version:       go1.15beta1

**Comment by roidelapluie** [comment]
```
data/wal
├── 00000040
├── 00000041
├── 00000042
├── 00000043
├── 00000044
└── checkpoint.00000039
    └── 00000000
data/chunks_head/
├── 000021
├── 000022
├── 000023
└── 000025
```

**Comment by roidelapluie** [comment]
```
  File: data/chunks_head/000021
  Size: 243             Blocks: 8          IO Block: 4096   regular file
Device: fe02h/65026d    Inode: 14629236    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/roidelapluie)   Gid: ( 1000/roidelapluie)
Access: 2020-06-17 20:03:16.291576192 +0200
Modify: 2020-06-17 20:01:12.089588968 +0200
Change: 2020-06-17 20:01:12.089588968 +0200
 Birth: -
  File: data/chunks_head/000022
  Size: 17633           Blocks: 40         IO Block: 4096   regular file
Device: fe02h/65026d    Inode: 14629237    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/roidelapluie)   Gid: ( 1000/roidelapluie)
Access: 2020-06-17 20:03:16.291576192 +0200
Modify: 2020-06-17 20:01:33.220584791 +0200
Change: 2020-06-17 20:01:33.220584791 +0200
 Birth: -
  File: data/chunks_head/000023
  Size: 478             Blocks: 8          IO Block: 4096   regular file
Device: fe02h/65026d    Inode: 14629259    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/roidelapluie)   Gid: ( 1000/roidelapluie)
Access: 2020-06-17 20:05:09.661586106 +0200
Modify: 2020-06-17 20:03:33.079576479 +0200
Change: 2020-06-17 20:03:33.079576479 +0200
 Birth: -
  File: data/chunks_head/000025
  Size: 8               Blocks: 8          IO Block: 4096   regular file
Device: fe02h/65026d    Inode: 14629258    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/roidelapluie)   Gid: ( 1000/roidelapluie)
Access: 2020-06-17 20:14:49.672833113 +0200
Modify: 2020-06-17 20:05:40.091591702 +0200
Change: 2020-06-17 20:05:40.091591702 +0200
 Birth: -
```

**Comment by roystchiang** [comment]
I also ran into the same issue

**What did you do?**
* Downloaded Prometheus 2.19.0 release
* Configured it scrape local Mac instance with NodeExporter
* Start Prometheus
* Stop Prometheus instance via CTRL + C
* Start Prometheus

**What did you expect to see?**
* I expected Prometheus to survive a restart

**What did you see instead? Under which circumstances?**
Got `level=error ts=2020-06-17T16:25:22.200Z caller=main.go:758 err="opening storage failed: found unsequential head chunk files 138 and 140"` instead

**Environment**

* System information:
        Darwin 18.7.0 x86_64

* Prometheus version:
	  build user:       root@d4cf5c7e268d
          build date:       20200609-10:38:50
          go version:       go1.14.4

* Alertmanager version:

	Don't have it

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'prometheus2'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'prometheus3'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'prometheus4'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['localhost:9100']

remote_write:
- url: http://localhost:9009/api/prom/push
```

* Alertmanager configuration file:
        Didn't configure it


* Logs:

Initial start up
```
38f9d365a6c0:prometheus-2.19.0.darwin-amd64 roychi$ ./prometheus --config.file=./prometheus.yml.bk
level=info ts=2020-06-17T16:21:56.453Z caller=main.go:302 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-06-17T16:21:56.453Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.19.0, branch=HEAD, revision=5d7e3e970602c755855340cb190a972cebdd2ebf)"
level=info ts=2020-06-17T16:21:56.453Z caller=main.go:338 build_context="(go=go1.14.4, user=root@d4cf5c7e268d, date=20200609-10:38:50)"
level=info ts=2020-06-17T16:21:56.453Z caller=main.go:339 host_details=(darwin)
level=info ts=2020-06-17T16:21:56.453Z caller=main.go:340 fd_limits="(soft=256, hard=unlimited)"
level=info ts=2020-06-17T16:21:56.453Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-06-17T16:21:56.469Z caller=main.go:678 msg="Starting TSDB ..."
level=info ts=2020-06-17T16:21:56.476Z caller=web.go:524 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-06-17T16:21:56.499Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1591995431990 maxt=1592006400000 ulid=01EAP0S2ZKYF7XXVXEXMAX89M7
level=info ts=2020-06-17T16:21:56.500Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592006400000 maxt=1592049600000 ulid=01EAWNMNVZSFAB19RXKCVDCES2
level=info ts=2020-06-17T16:21:56.501Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592229600000 maxt=1592265600000 ulid=01EAXQZ6BWHJVTTK9EAZ7DP2T9
level=info ts=2020-06-17T16:21:56.501Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592265600000 maxt=1592330400000 ulid=01EAZEX10NXK9Z0K9NFX8JKWR7
level=info ts=2020-06-17T16:21:56.501Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592352000000 maxt=1592359200000 ulid=01EB03G4WN5N4EAZV7E53P73CS
level=info ts=2020-06-17T16:21:56.502Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592330400000 maxt=1592352000000 ulid=01EB03G5JVB7ZMN1BQDQXTZBND
level=info ts=2020-06-17T16:21:56.502Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592359200000 maxt=1592366400000 ulid=01EB1D0JQS3RF698E0N091JWY1
level=info ts=2020-06-17T16:21:56.529Z caller=head.go:645 component=tsdb msg="Replaying WAL and on-disk memory mappable chunks if any, this may take a while"
level=warn ts=2020-06-17T16:21:56.621Z caller=head.go:628 component=tsdb msg="Unknown series references" count=111668
level=info ts=2020-06-17T16:21:56.621Z caller=head.go:682 component=tsdb msg="WAL checkpoint loaded"
level=info ts=2020-06-17T16:21:56.628Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=193 maxSegment=196
level=info ts=2020-06-17T16:21:56.628Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=194 maxSegment=196
level=info ts=2020-06-17T16:21:56.677Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=195 maxSegment=196
level=info ts=2020-06-17T16:21:56.677Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=196 maxSegment=196
level=info ts=2020-06-17T16:21:56.677Z caller=head.go:709 component=tsdb msg="WAL replay completed" duration=148.578674ms
level=info ts=2020-06-17T16:21:56.680Z caller=main.go:694 fs_type=19
level=info ts=2020-06-17T16:21:56.680Z caller=main.go:695 msg="TSDB started"
level=info ts=2020-06-17T16:21:56.680Z caller=main.go:799 msg="Loading configuration file" filename=./prometheus.yml.bk
ts=2020-06-17T16:21:56.688Z caller=dedupe.go:112 component=remote level=info remote_name=9ecaec url=http://localhost:9009/api/prom/push msg="Starting WAL watcher" queue=9ecaec
ts=2020-06-17T16:21:56.688Z caller=dedupe.go:112 component=remote level=info remote_name=9ecaec url=http://localhost:9009/api/prom/push msg="Replaying WAL" queue=9ecaec
level=info ts=2020-06-17T16:21:56.916Z caller=main.go:827 msg="Completed loading of configuration file" filename=./prometheus.yml.bk
level=info ts=2020-06-17T16:21:56.917Z caller=main.go:646 msg="Server is ready to receive web requests."
ts=2020-06-17T16:22:01.936Z caller=dedupe.go:112 component=remote level=info remote_name=9ecaec url=http://localhost:9009/api/prom/push msg="Done replaying WAL" duration=5.248497548s
level=info ts=2020-06-17T16:22:01.995Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.431907ms
level=info ts=2020-06-17T16:22:02.045Z caller=head.go:869 component=tsdb msg="WAL checkpoint complete" first=193 last=194 duration=40.102986ms
level=info ts=2020-06-17T16:22:02.096Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.939833ms
level=info ts=2020-06-17T16:22:02.157Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.279883ms
level=info ts=2020-06-17T16:22:02.240Z caller=head.go:869 component=tsdb msg="WAL checkpoint complete" first=195 last=196 duration=71.239701ms
level=info ts=2020-06-17T16:22:02.285Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.298467ms
level=info ts=2020-06-17T16:22:02.341Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=1.412763ms
level=info ts=2020-06-17T16:22:02.406Z caller=head.go:869 component=tsdb msg="WAL checkpoint complete" first=197 last=198 duration=58.08393ms
```

On shutdown
```
^Clevel=warn ts=2020-06-17T16:25:21.523Z caller=main.go:524 msg="Received SIGTERM, exiting gracefully..."
level=info ts=2020-06-17T16:25:21.523Z caller=main.go:547 msg="Stopping scrape discovery manager..."
level=info ts=2020-06-17T16:25:21.530Z caller=main.go:561 msg="Stopping notify discovery manager..."
level=info ts=2020-06-17T16:25:21.530Z caller=main.go:583 msg="Stopping scrape manager..."
level=info ts=2020-06-17T16:25:21.530Z caller=main.go:543 msg="Scrape discovery manager stopped"
level=info ts=2020-06-17T16:25:21.530Z caller=main.go:557 msg="Notify discovery manager stopped"
level=info ts=2020-06-17T16:25:21.538Z caller=main.go:577 msg="Scrape manager stopped"
level=info ts=2020-06-17T16:25:21.538Z caller=manager.go:882 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-06-17T16:25:21.544Z caller=manager.go:892 component="rule manager" msg="Rule manager stopped"
ts=2020-06-17T16:25:21.562Z caller=dedupe.go:112 component=remote level=info remote_name=9ecaec url=http://localhost:9009/api/prom/push msg="Stopping remote storage..."
ts=2020-06-17T16:25:21.569Z caller=dedupe.go:112 component=remote level=info remote_name=9ecaec url=http://localhost:9009/api/prom/push msg="WAL watcher stopped" queue=9ecaec
ts=2020-06-17T16:25:21.571Z caller=dedupe.go:112 component=remote level=info remote_name=9ecaec url=http://localhost:9009/api/prom/push msg="Remote storage stopped."
level=info ts=2020-06-17T16:25:21.604Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2020-06-17T16:25:21.606Z caller=main.go:749 msg="Notifier manager stopped"
level=info ts=2020-06-17T16:25:21.606Z caller=main.go:761 msg="See you next time!"
```

On restart
```
38f9d365a6c0:prometheus-2.19.0.darwin-amd64 roychi$ ./prometheus --config.file=./prometheus.yml.bk
level=info ts=2020-06-17T16:25:22.191Z caller=main.go:302 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-06-17T16:25:22.191Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.19.0, branch=HEAD, revision=5d7e3e970602c755855340cb190a972cebdd2ebf)"
level=info ts=2020-06-17T16:25:22.191Z caller=main.go:338 build_context="(go=go1.14.4, user=root@d4cf5c7e268d, date=20200609-10:38:50)"
level=info ts=2020-06-17T16:25:22.191Z caller=main.go:339 host_details=(darwin)
level=info ts=2020-06-17T16:25:22.191Z caller=main.go:340 fd_limits="(soft=256, hard=unlimited)"
level=info ts=2020-06-17T16:25:22.191Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-06-17T16:25:22.193Z caller=main.go:678 msg="Starting TSDB ..."
level=info ts=2020-06-17T16:25:22.193Z caller=web.go:524 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-06-17T16:25:22.193Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1591995431990 maxt=1592006400000 ulid=01EAP0S2ZKYF7XXVXEXMAX89M7
level=info ts=2020-06-17T16:25:22.194Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592006400000 maxt=1592049600000 ulid=01EAWNMNVZSFAB19RXKCVDCES2
level=info ts=2020-06-17T16:25:22.194Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592229600000 maxt=1592265600000 ulid=01EAXQZ6BWHJVTTK9EAZ7DP2T9
level=info ts=2020-06-17T16:25:22.194Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592265600000 maxt=1592330400000 ulid=01EAZEX10NXK9Z0K9NFX8JKWR7
level=info ts=2020-06-17T16:25:22.195Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592352000000 maxt=1592359200000 ulid=01EB03G4WN5N4EAZV7E53P73CS
level=info ts=2020-06-17T16:25:22.195Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592330400000 maxt=1592352000000 ulid=01EB03G5JVB7ZMN1BQDQXTZBND
level=info ts=2020-06-17T16:25:22.195Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592359200000 maxt=1592366400000 ulid=01EB1D0JQS3RF698E0N091JWY1
level=info ts=2020-06-17T16:25:22.199Z caller=main.go:547 msg="Stopping scrape discovery manager..."
level=info ts=2020-06-17T16:25:22.200Z caller=main.go:561 msg="Stopping notify discovery manager..."
level=info ts=2020-06-17T16:25:22.200Z caller=main.go:583 msg="Stopping scrape manager..."
level=info ts=2020-06-17T16:25:22.200Z caller=main.go:557 msg="Notify discovery manager stopped"
level=info ts=2020-06-17T16:25:22.200Z caller=main.go:543 msg="Scrape discovery manager stopped"
level=info ts=2020-06-17T16:25:22.200Z caller=manager.go:882 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-06-17T16:25:22.200Z caller=main.go:577 msg="Scrape manager stopped"
level=info ts=2020-06-17T16:25:22.200Z caller=manager.go:892 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-06-17T16:25:22.200Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2020-06-17T16:25:22.200Z caller=main.go:749 msg="Notifier manager stopped"
level=error ts=2020-06-17T16:25:22.200Z caller=main.go:758 err="opening storage failed: found unsequential head chunk files 138 and 140"
```

listing data/chunks_head
```
38f9d365a6c0:prometheus-2.19.0.darwin-amd64 roychi$ ls data/chunks_head/
000135  000136  000137  000138  000140  000141  000145  000146
```

I ran into this issue 3 times in the 7 days I have been using Prometheus, so I suspect it's not an one-off issue.

Please let me know if more information is required.

**Comment by codesome** [comment]
Thanks for the details. I will investigate it today. In the meanwhile, if anyone is facing this issue, they can delete all the m-mapped files after the point where the unsequential files start without any data loss.

**Comment by roidelapluie** [comment]
Note: Prometheus was starting with debug logging but there was no debug
message from TSDB.

Le jeu. 18 juin 2020 à 07:33, Ganesh Vernekar <notifications@github.com> a
écrit :

**Comment by codesome** [comment]
@roidelapluie @roystchiang are the exporters exposing some timestamp?

I can see a place where this is possible and the fix is simple. During [deletion of files](https://github.com/prometheus/prometheus/blob/d634785944e1416245c97c7d176601d9e57dbd50/tsdb/chunks/head_chunks.go#L672-L679) it does not stop after the first file which does not satisfy the deletion criteria and checks all the files, and it's possible some file in the middle might satisfy it.

**Comment by roidelapluie** [comment]
In my case it was scraping one Prometheus server and 5 targets down; so only a few hundreds metrics, without timestamp. This is on my laptop.

**Comment by codesome** [comment]
I see another possible scenario:
1. A new file is just cut as it got full. Let's say file 23 was full, and now its file 24 which is new.
2. And shortly, before any chunk was written to 24, head compaction happened and a new file was created, 25. Hence 24 was left empty.
3. As 24 has 0 chunks, its maxt is 0. Hence during next truncation, 24 is deleted as we are checking all files.

We can do 2 fixes here: 
(1) Don't cut a new file on compaction if the current file is empty.
(2) Stop truncating files after we hit a file which does not require deletion.

**Comment by roidelapluie** [comment]
Given that my Prometheus was very low traffic that is very possible

**Comment by codesome** [comment]
Fixed in https://github.com/prometheus/prometheus/pull/7414

**Comment by unixlab** [comment]
Hey!

I'm still seeing this with prometheus 2.19.1.

Steps to reproduce:
1. download prometheus 2.19.1 and unarchive it
2. copy my data directory in the unarchived directory
3. start prometheus with the default configuration

```
11:53:17 ~/Downloads/prometheus-2.19.1.linux-amd64 $ ./prometheus 
level=info ts=2020-06-19T09:54:20.848Z caller=main.go:302 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-06-19T09:54:20.848Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.19.1, branch=HEAD, revision=eba3fdcbf0d378b66600281903e3aab515732b39)"
level=info ts=2020-06-19T09:54:20.848Z caller=main.go:338 build_context="(go=go1.14.4, user=root@62700b3d0ef9, date=20200618-16:35:26)"
level=info ts=2020-06-19T09:54:20.848Z caller=main.go:339 host_details="(Linux 5.6.16-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:26:28 UTC 2020 x86_64 flixbook (none))"
level=info ts=2020-06-19T09:54:20.848Z caller=main.go:340 fd_limits="(soft=1024, hard=524288)"
level=info ts=2020-06-19T09:54:20.848Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-06-19T09:54:20.849Z caller=web.go:524 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-06-19T09:54:20.849Z caller=main.go:678 msg="Starting TSDB ..."
level=info ts=2020-06-19T09:54:20.849Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1576389600000 maxt=1578139200000 ulid=01DY3MC0F2A56WPGK2S6EYSXSS
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1578139200000 maxt=1578722400000 ulid=01DY9XA8MXS0SHJBBMBKGB5XC0
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1578722400000 maxt=1579305600000 ulid=01DYZQSQ8Z9F1KR9RTYQZD4QNB
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1579305600000 maxt=1579888800000 ulid=01E11CF4ANKRS8D31YZXABJ9PQ
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1579888800000 maxt=1580472000000 ulid=01E11CF4RXP64T6Y4NKFDGC084
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1580472000000 maxt=1581055200000 ulid=01E11CF57KEP88N2THMGE7WP2E
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1581055200000 maxt=1581638400000 ulid=01E11CF5P0E1H1QYFRFSBATGYJ
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1581638400000 maxt=1582221600000 ulid=01E1J6DD6G2VSQ7MWB4ZW55VDE
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1582221600000 maxt=1582804800000 ulid=01E23JK7RBXZF4C4RQA30RMX61
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1582804800000 maxt=1583388000000 ulid=01E2MYS3KC80Q2CQFXF0C4F86X
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1583388000000 maxt=1583971200000 ulid=01E36AYYFV9TCTKRCEN5N21ZDH
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1583971200000 maxt=1584554400000 ulid=01E3QQ4QH6236J019B36RZXDCH
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1584554400000 maxt=1585137600000 ulid=01E493AMC4XP367PQ0Z2ZNC15J
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1585137600000 maxt=1585720800000 ulid=01E4TFGFMW1V4BWQJTBFGS5YQ9
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1585720800000 maxt=1586304000000 ulid=01E5BVPB8QA6QX8YY4REHS3J6N
level=info ts=2020-06-19T09:54:20.850Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1586304000000 maxt=1586887200000 ulid=01E5X7W6JGH1W6G02CYYS3C935
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1586887200000 maxt=1587470400000 ulid=01E6EM1ZF0F58NZZD3EKT54MMV
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1587470400000 maxt=1588053600000 ulid=01E7007TASB9KEARS2Z1Z5VWRM
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1588053600000 maxt=1588636800000 ulid=01E7HCDRMVF4CTPMF3MKSTVXVC
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1588636800000 maxt=1589220000000 ulid=01E82RKMGMYQRGAP55R6SN6CGQ
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1589220000000 maxt=1589803200000 ulid=01E8M4SEMKM4YS8BB3CJXKS260
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1589803200000 maxt=1590386400000 ulid=01E95GYZRBWWJMSD01YPJ6B2JW
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1590386400000 maxt=1590969600000 ulid=01E9PX4TZ1FJF4WGP32Y6NK8SD
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1590969600000 maxt=1591552800000 ulid=01EA89AQJC0VW5MEQ9GW4CEKW1
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1591552800000 maxt=1592136000000 ulid=01EASNGS84DV99NZBSDWTAS7FN
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592136000000 maxt=1592330400000 ulid=01EAZEXEEPTW1G7D3QDE3MZF02
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592330400000 maxt=1592524800000 ulid=01EB58A1X5Z3HFMQZNM7Y2E217
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592546400000 maxt=1592553600000 ulid=01EB5WX68JDA507D8ZWVK78H0Y
level=info ts=2020-06-19T09:54:20.851Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1592524800000 maxt=1592546400000 ulid=01EB5WX70T1YWK4C4326EFRYQ0
level=info ts=2020-06-19T09:54:20.853Z caller=main.go:547 msg="Stopping scrape discovery manager..."
level=info ts=2020-06-19T09:54:20.853Z caller=main.go:561 msg="Stopping notify discovery manager..."
level=info ts=2020-06-19T09:54:20.854Z caller=main.go:583 msg="Stopping scrape manager..."
level=info ts=2020-06-19T09:54:20.854Z caller=main.go:557 msg="Notify discovery manager stopped"
level=info ts=2020-06-19T09:54:20.854Z caller=main.go:543 msg="Scrape discovery manager stopped"
level=info ts=2020-06-19T09:54:20.854Z caller=manager.go:882 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-06-19T09:54:20.854Z caller=manager.go:892 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-06-19T09:54:20.854Z caller=main.go:577 msg="Scrape manager stopped"
level=info ts=2020-06-19T09:54:20.854Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2020-06-19T09:54:20.854Z caller=main.go:749 msg="Notifier manager stopped"
level=error ts=2020-06-19T09:54:20.854Z caller=main.go:758 err="opening storage failed: found unsequential head chunk files 5 and 7"
```

If it helps I would be willing to send you my data directory (422 MB) in a non-public way.

**Comment by codesome** [comment]
@unixlab  Can you show the contents (just the file names) inside the `chunks_head` directory before the upgrade?

**Comment by unixlab** [comment]
```
12:17:17 ~/Downloads/data/chunks_head $ ll
total 164K
4.0K drwxr-xr-x  2 felix felix 4.0K Jun 10 12:30 .
4.0K drwxr-xr-x 34 felix felix 4.0K Jun 19 11:00 ..
148K -rw-r--r--  1 felix felix 148K Jun 10 12:11 000005
4.0K -rw-r--r--  1 felix felix    8 Jun 10 12:30 000007
4.0K -rw-r--r--  1 felix felix    8 Jun 10 12:30 000008
```

**Comment by codesome** [comment]
The unsequential files here were created by 2.19.0. Can you delete 7 and 8 and then run 2.19.1? It should not occur again after that.

**Comment by unixlab** [comment]
Works after deleting 7 and 8, but after reading the issue I assumed that 2.19.1 would work without manual deleting the files. Maybe that was my misunderstanding.

**Comment by justinmchase** [comment]
I just got this error and I'm running version `2.23.0`, not sure if its a regression or just not completely fixed?

**Comment by justinmchase** [comment]
```
level=info ts=2021-07-26T19:24:48.301Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1627063200000 maxt=1627084800000 ulid=01FBB7989MC0WVH5J65E374WQ9
level=info ts=2021-07-26T19:24:48.538Z caller=main.go:595 msg="Stopping scrape discovery manager..."
level=info ts=2021-07-26T19:24:48.538Z caller=main.go:609 msg="Stopping notify discovery manager..."
level=info ts=2021-07-26T19:24:48.538Z caller=main.go:631 msg="Stopping scrape manager..."
level=info ts=2021-07-26T19:24:48.538Z caller=main.go:605 msg="Notify discovery manager stopped"
level=info ts=2021-07-26T19:24:48.538Z caller=manager.go:924 component="rule manager" msg="Stopping rule manager..."
level=info ts=2021-07-26T19:24:48.539Z caller=manager.go:934 component="rule manager" msg="Rule manager stopped"
level=info ts=2021-07-26T19:24:48.539Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2021-07-26T19:24:48.539Z caller=main.go:799 msg="Notifier manager stopped"
level=info ts=2021-07-26T19:24:48.538Z caller=main.go:591 msg="Scrape discovery manager stopped"
level=info ts=2021-07-26T19:24:48.539Z caller=main.go:625 msg="Scrape manager stopped"
level=error ts=2021-07-26T19:24:48.539Z caller=main.go:808 err="opening storage failed: found unsequential head chunk files /data/chunks_head/000013 (index: 13) and /data/chunks_head/000271 (index: 271)"
```

```sh
/prometheus $ ls -la /data/chunks_head
total 1340
drwxr-xr-x    2 1001     root          4096 Jul 24 03:00 .
drwxrwxrwx   26 root     root          4096 Jul 24 03:00 ..
-rw-r--r--    1 1001     root          2658 Jul  2 14:03 000013
-rw-r--r--    1 1001     root        664184 Jul 24 03:00 000271
-rw-r--r--    1 1001     root        682673 Jul 24 04:19 000272
```

No idea how that's possible...

**Comment by yauh-ask** [comment]
@codesome thank you for clarification!
We are already running:
`prometheus-chart-14.6.0, version 2.26.0`
By the latest release, do you mean chart 14.11?

**Comment by codesome** [comment]
Latest _Prometheus_ version, which would be `v2.31.1`. I am not familiar with the charts.
