### ISSUE TITLE
PromQL: `histogram_quantile` has a possible off-by-one error

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#7970]
https://linuxczar.net/blog/2020/08/13/histogram-error/ claims that the interpolation that the `histogram_quantile` function performs within a bucket overestimates, which becomes most prominent with low numbers of samples in the bucket. IIUC, the blog post claims `histogram_quantile` interpolates as

Q(p) = lower_bound + bucket_width * k / n

where it should do

Q(p) = lower_bound + bucket_width * k / (n+1)

I think there is a bit more nuance how k is determined: It's rare that there is a _k_ that represents exactly the desired rank, and you have to pick the one before or after or the closest. I don't remember what exactly `histogram_quantile` does here, possibly an interpolation again, and the way it does that will interact with the right formula to use. I mostly file this bug to remind myself to properly research it.

In any case, this problem will only happen with small sample counts in the bucket and is therefore only relevant when the statistical error is high anyway. I see it therefore as less dramatic as it sounds in the blog post. Still, if this is an unnecessary additional error, we should get rid of it.

(In different news, the maximum possible error with any kind of interpolation is always the bucket width. To minimize the theoretical maximum of the relative error, the harmonic mean has to be taken, no matter where in the bucket population _k_ is. Interpolation vs. harmonic mean is essentially a tradeoff between minimizing the expected average error and having a strict theoretical upper limit of the relative error. This will be a point of discussion for the upcoming new histogram implementation.)

**Comment by roidelapluie** [comment]
Was it fixed by  #7393 ?

**Comment by beorn7** [comment]
Maybe, but I'm not sure. Will have a thorough look once I find time.

**Comment by jjneely** [comment]
#7393 does not fix this.  (Oh wow, that's a subtle bug...being I wrote the ensureMonotonic bits I guess I gotta own that one.)

My article was comparing the linear approximation Prometheus does with other algorithms other vendors use.  The code in question is here:

https://github.com/prometheus/prometheus/blob/master/promql/quantile.go#L114

```
bucketStart + (bucketEnd-bucketStart)*(rank/count)
```

There are fewer samples at the tails obviously, and it is the tails that are the most interesting.  So the worst case of 1 sample in a bucket (or less since we've used `rate()`) is probably frequent.  In traditional histograms where count is an integer we might have `rank=0` and `count=1` or `rank=1` and `count=1`.  This produces the entire bucket width as possible error.  Taking a Beta Distribution gives us the average probable location in the bucket.  That's `rank/(count+1)`.  For single sample buckets that's 1/2 and means the possible error is half the bucket width.   

Here `count` and `rank` are floats and rank is not the ceil(q * observations).  This makes me doubt that this is an easy fix to help improve accuracy.

**Comment by beorn7** [comment]
Thanks for the explanation. I'll have a closer look ASAP.

**Comment by beorn7** [comment]
In #9553, I added a few test cases. Those cover the case where the interpolation is supposed to find the middle of the bucket. The test cases prove that this works even with a single sample in the bucket in question. I think this works because we already accept fractions in the `rank`.

So #9553 falsifies the following sentence from the [blog post mentioned above](https://linuxczar.net/blog/2020/08/13/histogram-error/): “Worst case is one sample in the bin and the interpolated value will be the upper bound of the bucket leaving the full bucket with for possible error spread.”

I think the reference to the beta distribution is somewhat misleading. Which beta distribution to take has more to do with assumptions of the distributions of samples within the bucket. `histogram_quantile` simply assumes an equal distribution of samples within the bucket. I think that's a reasonable assumption given that users set bucket boundaries as they see fit. And from all I can see, the current implementation correctly mirrors that assumption. The most intuitive results thereof are perhaps these two:
* If the quantile coincides with one sample (e.g. the median in a sample size of three), and that one sample is the only one in a particular bucket, the current implementation will calculate the midpoint of that bucket as the estimated quantile value.
* If the quantile is just in between two values (e.g. the median in a sample size of two), and those end up in consecutive buckets, the current implementation will calculate the bucket boundary between those two buckets as the estimated quantile value.

With a pre-defined exponential bucketing schema (as we are currently exploring for the new sparse high-res histograms), things look a bit different, and we should explore in more details what distribution within the bucket we should assume for any interpolation (or, alternatively, if just always taking some midpoint (e.g. the harmonic mean), might be better since it limits the maximum possible error at the price of increasing the expectation value for the error). But that's a different area of research (and it will be taken into account when we implement quantile calculation based on the new sparse high-res histograms).

**Comment by beorn7** [comment]
I close this for now, as I'm fairly confident there is no "off by one" error, but feel free to update with more evidence.
