### ISSUE TITLE
Compaction fails when total symbol size exceeds 2^32 bytes

### ISSUE THREAD

**Issue by t00350320** [prometheus/prometheus#9078]
**What did you do?**
compact blocks from 7 2day files  to larger one by thanos.   duration=300

**What did you expect to see?**
7*2day blocks can be compacted successfully.

**What did you see instead? Under which circumstances?**
normal compact process halt, and throw this error " 2 errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum"

**Environment**
4C16G , block files index is 1.5G,4.2g,4.13g,3.74g,5.24g,5.25g,5.06g
* System information:

	insert output of `uname -srm` here

* Prometheus version:
     1.8.2
	insert output of `prometheus --version` here

* Logs:
```
caller=compact.go:416 msg="critical error detected; halting" err="compaction: group 300@14327834599727325097: compact blocks [xx,xx,xx,xx,xx,xx,xx]: 2 errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum"

code info:
thanos compact/compact.go 
     comp.Compact(dir,plan,nil)

tsdb/compact.go
  L380  Compact
  L424 c.write(dest,meta,blocks)
         c.populateBlock
              indexw.AddSeries(ref,sl,chks...) ??

**Comment by liubo-it** [comment]
good

**Comment by LeviHarrison** [comment]
What OS are you using? I know we've had problems with OpenBSD.

https://github.com/prometheus/prometheus/issues/8877

**Comment by t00350320** [comment]
Centos





------------------ Original ------------------
From: Levi Harrison ***@***.***&gt;
Date: Wed,Jul 14,2021 10:11 AM
To: prometheus/prometheus ***@***.***&gt;
Cc: Jupiter ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [prometheus/prometheus] when compact blocks, err "errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum" (#9078)





 
What OS are you using? I know we've had problems with OpenBSD.
 
#8877

**Comment by t00350320** [comment]
now,i change to a 16C-64G envirnment, when above invalid error occurs, the %MEM only reach 40%. So we can see this issue may has no relation with MEM size.  

if i compact the front 6 blocks, it works well
if i compact the back 6 blocks, it works well too.   
When this error info occurs in compact 7 blocks, the process only pass 40s;  but when front or back 6 block compacted successfully, it passed half an hour. 
So ,Any one has a idea, 
1、how and when the tsdb read symbols and why it think invalid？
2、every block's index and chunks are read into memery or write to disk at the same time?

**Comment by t00350320** [comment]
error code area:
github.com/prometheus/prometheus/tsdb/encoding/encoding.go
func NewDecbufAt(bs ByteSlice, off int, castagnoliTable *crc32.Table) Decbuf {
...
        if castagnoliTable != nil {
                if exp := binary.BigEndian.Uint32(b[len(b)-4:]); dec.Crc32(castagnoliTable) != exp {
                        fmt.Println("exp,dec.Crc32",exp,dec.Crc32(castagnoliTable))
                        debug.PrintStack()
                        return Decbuf{E: ErrInvalidChecksum}
                }
        }
...}

stack info:

        /usr/local/go/src/runtime/debug/stack.go:16 +0x25
hash/crc32.archUpdateCastagnoli(0x35933015, 0x7fa5fb604190, 0x2e6, 0x1000002ea, 0xc0ca6ccfea)
        /usr/local/go/src/hash/crc32/crc32_amd64.go:193 +0x3de
hash/crc32.Update(0xc000000000, 0xc000170400, 0x7fa5f5cf4009, 0x591046d, 0x105910471, 0x1ca6ccfea)
        /usr/local/go/src/hash/crc32/crc32.go:215 +0x11a
hash/crc32.Checksum(...)
        /usr/local/go/src/hash/crc32/crc32.go:249
github.com/prometheus/prometheus/tsdb/encoding.(*Decbuf).Crc32(...)
        /opt/ts/tshouse-thanos/vendor/github.com/prometheus/prometheus/tsdb/encoding/encoding.go:180
github.com/prometheus/prometheus/tsdb/encoding.NewDecbufAt(0xb7d9c0, 0xc0148b2780, 0x5, 0xc000170400, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/ts/tshouse-thanos/vendor/github.com/prometheus/prometheus/tsdb/encoding/encoding.go:126 +0x23c
github.com/prometheus/prometheus/tsdb/index.NewSymbols(0xb7da00, 0xc0148b2780, 0x2, 0x5, 0x105910476, 0x0, 0x0)
        /opt/ts/tshouse-thanos/vendor/github.com/prometheus/prometheus/tsdb/index/index.go:1246 +0xd0
github.com/prometheus/prometheus/tsdb/index.(*Writer).finishSymbols(0xc000284f00, 0xc001b484e0, 0x0)
        /opt/ts/tshouse-thanos/vendor/github.com/prometheus/prometheus/tsdb/index/index.go:534 +0x3cb
github.com/prometheus/prometheus/tsdb/index.(*Writer).ensureStage(0xc000284f00, 0xc000000102, 0xc000036000, 0xc00108ee78)
        /opt/ts/tshouse-thanos/vendor/github.com/prometheus/prometheus/tsdb/index/index.go:359 +0x273
github.com/prometheus/prometheus/tsdb/index.(*Writer).AddSeries(0xc000284f00, 0x0, 0xc00031c3c0, 0x6, 0x6, 0xc0003518c0, 0x1, 0x1, 0x0, 0x0)
        /opt/ts/tshouse-thanos/vendor/github.com/prometheus/prometheus/tsdb/index/index.go:408 +0x48
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).populateBlock(0xc0001aafa0, 0xc00019e280, 0x7, 0x8, 0xc0001f46c0, 0xb82060, 0xc000284f00, 0xb7b7c0, 0xc0001aa960, 0x0, ...)
        /opt/ts/tshouse-thanos/vendor/github.com/prometheus/prometheus/tsdb/compact.go:783 +0x1345 
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).write(0xc0001aafa0, 0x7ffd24b428dd, 0x65, 0xc0001f46c0, 0xc00019e280, 0x7, 0x8, 0x0, 0x0)
        /opt/ts/tshouse-thanos/vendor/github.com/prometheus/prometheus/tsdb/compact.go:582 +0x5d8
github.com/prometheus/prometheus/tsdb.(*LeveledCompactor).Compact(0xc0001aafa0, 0x7ffd24b428dd, 0x65, 0xc00019ea80, 0x7, 0x8, 0x0, 0x0, 0x0, 0xea51d4b131a97a01, ...)
        /opt/ts/tshouse-thanos/vendor/github.com/prometheus/prometheus/tsdb/compact.go:424 +0x617
main.main()
        /opt/ts/tshouse-thanos/pkg/compact/tsdb.go:104 +0xc43
crc,^crc 898838549 3396128746
exp,dec.Crc32 1697605998 3396128746

**Comment by t00350320** [comment]
Hi，i have added more infos,pls help to review that. Our tsdb take lots service datas,&nbsp;
a monitor metric’s label&nbsp;may change as time flows, it also may be dropped at some chunk.So may this affect the final compact. i also find the tsdb code try to add series from chunks according a global index symbol





------------------ Original ------------------
From: Levi Harrison ***@***.***&gt;
Date: Wed,Jul 14,2021 10:11 AM
To: prometheus/prometheus ***@***.***&gt;
Cc: Jupiter ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [prometheus/prometheus] when compact blocks, err "errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum" (#9078)





 
What OS are you using? I know we've had problems with OpenBSD.
 
#8877

**Comment by LeviHarrison** [comment]
Maybe related to https://github.com/thanos-io/thanos/issues/1728?

Also, what Thanos version are you using? I can't find `pkg/compact/tsdb.go` anywhere.

**Comment by t00350320** [comment]
prometheus version: 1.8.2
thanos version : 0.16.0 , #1728 has no conclusion now.
ah,compact/tsdb.go is my test tool according thanos/pkg/compact/compact.go . our current version may has much different with master. 
very confused and  sad -_-

**Comment by LeviHarrison** [comment]
Given the RC for `0.22.0` was just released, and it's been almost a year since `0.16.0` came out, you might want to try upgrading, although I know that might be difficult with your custom version. Thanos doesn't actually use version `1.8.2` of Prometheus (if it did there would be no `/tsdb` directory), so by upgrading you'd get both new Thanos and TSDB changes.

https://github.com/thanos-io/thanos/issues/1728 ends at the 64 GiB index limit, which seems to not have been fixed yet as #5884 isn't merged. I wonder how big the indexes in those blocks are, maybe it is that.

You may also want to file an issue in Thanos and see what they say.

**Comment by t00350320** [comment]
en, i try to use the latest prometheus version, then make my compact tool, the error also occurs. 
BTW, i think it has no business with thanos, because it also use the prometheus's compact interface.
the very simple tool  like:
        ctx, _ := context.WithCancel(context.Background())
        levels, err := compactions.levels(4)
        compDownSample, err := tsdb.NewLeveledCompactor(ctx, nil, logger, levels, downsample.NewPool(),nil)
       comps := map[int64]tsdb.Compactor{
                downsample.ResLevel1: compDownSample ,
                downsample.ResLevel2: compDownSample,
        }
       fmt.Println("start tsdb tool,plan",plan)
        var compID  [16]byte
        compID, err = comp.Compact(dir, plan, nil)

**Comment by t00350320** [comment]
Hi,LeviHarrison 
  i think i have dug out the  reason of my "invalid checksum":
index->symbol len is 4byte, but our service datas, reach to 4388357229, and it's cut down to 4byte. So the crc32 errors in the end.
prometheus/tsdb/index/index.go  func() finishSymbols
w.buf1.PutBE32int(int(w.f.pos - w.toc.Symbols - 4))
btw, thank you very much for your help and proposal.

**Comment by t00350320** [comment]
So, Can tsdb make some optimization ？@fabxc   @bwplotka @roidelapluie  please help to review. Thanks a lot.

**Comment by codesome** [comment]
@t00350320 thanks for your investigation, seems like you found the issue.

> So, Can tsdb make some optimization ？

Can you please elaborate on this?

**Comment by t00350320** [comment]
hi
root cause is :according to tsdb&nbsp;index file format, symbol_table part, first 4byte shows the length of total symbol strings of all the blocks being compacted. It works well at most time.
But our prometheus systerm has more than 10 million symbols. So the symbol_table part becomes really big. It’s larger than 4byte. In&nbsp;function finishsymbol()&nbsp;,&nbsp;the original symbolstr len is cut down to 4byte, like:
putbe32(f.pos-toc.symbol-4 )
When make crc32 hash to fill the index’ symbol_part’s crc32 zone, it use the cut down length . But at Newdecbuf crc32 check(newsymbol), it reads the original length.&nbsp;
So this the details. You can find all in func finishsymbol.




tadb compact blocks workflow like this:
func populateBlocks
&nbsp; &nbsp;addsymbols from all blocks.( now the new index file only has symbol info,but symbol length and crc32 have not been filled)
&nbsp; &nbsp;addchunk one by one (now the new chunk file start to make)
&nbsp; &nbsp;addseries of cur chunk(because all the symbols have been written to index, we need to finish symbols by filling symbol len and crc32(error pops up here). then the index of symbol_table part finished. &nbsp;series are appended...)







------------------ Original ------------------
From: Ganesh Vernekar ***@***.***&gt;
Date: Mon,Jul 19,2021 9:17 PM
To: prometheus/prometheus ***@***.***&gt;
Cc: Jupiter ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [prometheus/prometheus] when compact blocks, err "errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum"【tsdb/index/index.go】【cause found, need review！！！】 (#9078)





 
@t00350320 thanks for your investigation, seems like you found the issue.
  
So, Can tsdb make some optimization ？
  
Can you please elaborate on this?

**Comment by t00350320** [comment]
So can tsdb reserve 8byte for symbollen zone. We know fabulous amounts of IOT services will access to prometheus systerm.





------------------ Original ------------------
From: Jupiter ***@***.***&gt;
Date: Mon,Jul 19,2021 10:28 PM
To: reply+AJ4LJWC4PURI7GRR6VTLFVV7AFOF5EVBNHHDQNYUJQ ***@***.***&gt;
Subject: Re: [prometheus/prometheus] when compact blocks, err "errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum"【tsdb/index/index.go】【cause found, need review！！！】 (#9078)



hi
root cause is :according to tsdb index file format, symbol_table part, first 4byte shows the length of total symbol strings of all the blocks being compacted. It works well at most time.
But our prometheus systerm has more than 10 million symbols. So the symbol_table part becomes really big. It’s larger than 4byte. In function finishsymbol() , the original symbolstr len is cut down to 4byte, like:
putbe32(f.pos-toc.symbol-4 )
When make crc32 hash to fill the index’ symbol_part’s crc32 zone, it use the cut down length . But at Newdecbuf crc32 check(newsymbol), it reads the original length. 
So this the details. You can find all in func finishsymbol.




tadb compact blocks workflow like this:
func populateBlocks
&nbsp; &nbsp;addsymbols from all blocks.( now the new index file only has symbol info,but symbol length and crc32 have not been filled)
&nbsp; &nbsp;addchunk one by one (now the new chunk file start to make)
&nbsp; &nbsp;addseries of cur chunk(because all the symbols have been written to index, we need to finish symbols by filling symbol len and crc32(error pops up here). then the index of symbol_table part finished. &nbsp;series are appended...)







------------------ Original ------------------
From: Ganesh Vernekar ***@***.***&gt;
Date: Mon,Jul 19,2021 9:17 PM
To: prometheus/prometheus ***@***.***&gt;
Cc: Jupiter ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [prometheus/prometheus] when compact blocks, err "errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum"【tsdb/index/index.go】【cause found, need review！！！】 (#9078)





 
@t00350320 thanks for your investigation, seems like you found the issue.
  
So, Can tsdb make some optimization ？
  
Can you please elaborate on this?

**Comment by codesome** [comment]
I have few more questions for you:
1. What is the architecture of your system? 32 bit or 64 bit? (since you said IOT)
2. What is the number of series in that block?

You mentioned 10M symbols, and the 4 bytes in the [symbol table](https://github.com/prometheus/prometheus/blob/main/tsdb/docs/format/index.md#symbol-table) is the number of symbols which can easily hold the number 10M, and we are actually using 8 bytes for storing the byte offset of the symbol table in the [TOC](https://github.com/prometheus/prometheus/blob/main/tsdb/docs/format/index.md#toc). But I see that we are doing `int(<byte offset>)` when consuming it, which will end up being a 32 bit int in 32 bit architecture.

**Comment by codesome** [comment]
Ah I totally missed that `len` part in the symbol table. Making it 8 bytes is a big breaking change. While it might be possible to do it with versioning, we have to analyse how it might affect entire ecosystem (like if it will make running on 32 bit IoT systems impossible). And if we are going to bump up the version, we might as well spend some time in seeing what other things we could possibly improve, so it is not going to be a instant change.

That said, to fill up 2^32 bytes of symbol table with 11744785 symbols, the average size of symbol should be 365 bytes, which is very big and not ideal. You should try to analyse the labels and avoid any long label name/values.

PS: No issues with delayed replies, that's totally fine.

**Comment by t00350320** [comment]
yes, modify the index format length is not esay. I'll add an errlog and pull request later, when the actual length over 4byte.

**Comment by roidelapluie** [comment]
@codesome  now that https://github.com/prometheus/prometheus/pull/9104/files is fixed, can we close this?

**Comment by codesome** [comment]
#9104 only adds a log for this and does not fix the underlying issue. I think we should keep it open until we eventually fix this.

**Comment by alanprot** [comment]
I wonder if we can somehow leverage https://github.com/prometheus/prometheus/pull/11711 to create another `BlockPopulator` and shard the results blocks and prevent hitting the 64GB limit.

Thoughts?

**Comment by bwplotka** [comment]
I think we should also discuss if we shouldn't make this a known limitation by design, document it and keep it as is. Anything beyond 64GB limit (or even half of it) is basically physically un-queryable (too long to traverse all postings) and should be sharded to multiple blocks by series dimension.

Also I think the original error report is not valid anymore as Thanos handles this in a clean way, by [ignoring that compaction group](https://github.com/thanos-io/thanos/blob/390926c9ea73bfa1e8da1add0a9a20be70e51d30/cmd/thanos/compact.go#L760) and allowing users to shard manually (until auto vertical block sharding is done).

**Comment by beorn7** [comment]
Closing this in lieu of #5868 . The current plan is to port a Thanos feature to avoid compacting blocks that are too large.
The larger index size seems to be too complicated to get it in.
