### ISSUE TITLE
"promtool tsdb create-blocks-from rules" backfilled data is duplicated

### ISSUE THREAD

**Issue by Lingx9** [prometheus/prometheus#9288]
**Overview**
 I use promtool to backfill the data of the rules.  After the backfill was completed, it was found that the data was duplicated, and every 2 hours was regarded as an independent metric. (Although their labels are exactly the same)
1. my recording rule
```
groups:
  - name: saas_bandwidth
    interval: 1m
    rules:
    - record: job:saas_tx_bandwidth
      expr: rate(collectd_saas_transmit_bytes_total{}[2m]) * 8
    - record: saas_rx_bandwidth
      expr: rate(collectd_saas_receive_bytes_total{}[2m]) * 8
```
2. Duplicate data, 
command: `./promtool query range http://127.0.0.1:9099 'saas_rx_bandwidth{neId="320"}'  --start=1630342949 --end=1630374911 --step=300s`
![image](https://user-images.githubusercontent.com/89964135/131835025-f95b6b35-5cb4-4178-b923-8c2e7cb409c0.png)
3. every 2 hours are regarded as different metrics
   ![image](https://user-images.githubusercontent.com/89964135/131825768-06e5e6ea-53ce-483f-ad84-fc890d4b5588.png) 
![image](https://user-images.githubusercontent.com/89964135/131826027-945d0813-3549-4ad3-bb8b-dbfa133ef311.png)
![image](https://user-images.githubusercontent.com/89964135/131826054-533cd7d5-5637-413b-84e4-618331a30eef.png)

**Environment**
```
  prometheus, version 2.29.2 (branch: HEAD, revision: 752c4f11ae86effa9a46f017f2feb66730c67ed8)
  build user:       root@61bcc9848ade
  build date:       20210827-09:44:22
  go version:       go1.16.7
  platform:         linux/amd64

promtool, version 2.29.2 (branch: HEAD, revision: 752c4f11ae86effa9a46f017f2feb66730c67ed8)
  build user:       root@61bcc9848ade
  build date:       20210827-09:44:22
  go version:       go1.16.7
  platform:         linux/amd64
```

**I want to know if my usage is incorrect? How to solve it? **

**Comment by beorn7** [comment]
Maybe this has to do with staleness markers? Do we perhaps insert them at the end of a block? (This is a very wild guess…)

**Comment by JessicaGreben** [comment]
@beorn7 staleness marker support is not merged into this rule backfilling yet (ref: #8976 ). 

Currently I'm going to check the ordering of the labels, maybe I need to sort them before writing to tsdb. But in talking to @brian-brazil and @roidelapluie it seems that the labels should be ordered and the above query range output should not be possible so maybe there is a bug there. That is where I'm going to start looking.  Another consideration is I'm wondering what happens if we do not wait for compaction after the backfill. Im going to check that also.

**Comment by Lingx9** [comment]
> @Lingx9你能分享你执行的回填命令吗？
> 
> 关于重复数据，如果多次运行回填命令，每次都会创建数据。因此，如果您在同一时间范围内多次运行回填命令，这可能是导致重复数据的原因。
> 
> 我不知道为什么他们报告的不仅仅是一个系列，但让我调查一下并回复你。



![image](https://user-images.githubusercontent.com/89964135/131942512-22be1fdb-d025-45c0-ab44-b0e77b783c49.png)

**Comment by Lingx9** [comment]
> @Lingx9你能分享你执行的回填命令吗？
> 
> 关于重复数据，如果多次运行回填命令，每次都会创建数据。因此，如果您在同一时间范围内多次运行回填命令，这可能是导致重复数据的原因。
> 
> 我不知道为什么他们报告的不仅仅是一个系列，但让我调查一下并回复你。

My execution command: `./promtool  tsdb create-blocks-from rules --start=1630339200 --end=1630411200  test.yaml   --url http://127.0.0.1:9099 --output-dir="test_data/"`

In another environment, I only ran the backfill command once. There was no data duplication problem.
But the data is still regarded as a different series   

![image](https://user-images.githubusercontent.com/89964135/131942843-e5a02fc5-6357-432b-89b4-d488a49a82cd.png)

**Comment by Lingx9** [comment]
> @beorn7陈旧标记支持尚未合并到此规则回填中（参考：#8976）。
> 
> 目前我要检查标签的顺序，也许我需要在写入 tsdb 之前对它们进行排序。但是在与@brian-brazil和@roidelapluie 交谈时，似乎应该对标签进行排序并且上面的查询范围输出应该是不可能的，所以那里可能存在错误。这就是我要开始寻找的地方。另一个考虑是我想知道如果回填后我们不等待压实会发生什么。我也要去检查一下。

Is there any confirmation that this is a problem and not caused by my incorrect use?

**Comment by johnfzc** [comment]
Yes, this is a problem, it's not caused by your incorrect usage. If you zoom in closely you'll see there's overlap between the time periods thought it may be difficult to see with your flat line.

**Comment by JessicaGreben** [comment]
Did a little investigation and came up with a few things.  The overlap in data might be from staleness. There will be an extra 5 mins of data if the series terminates because the stale marker support isn't added to this backfill feature yet. 

Additionally there is another issue I discovered where the max time of the first blocks is greater than the min time of the next block by 1, which it should not be so I need to figure out why thats happening and fix it.  For example this is the block output from the rule backfiller:
```
$ ./promtool tsdb list data/
BLOCK ULID                  MIN TIME       MAX TIME       DURATION      NUM SAMPLES  NUM CHUNKS   NUM SERIES   SIZE
01FF0F4DEQ6PPEJKDYGVZ6M7A0  1630997895141  1631026755142  8h1m0.001s    1929         21           5            3177
01FF0PM6VTFE5JEX5N7QNDHPRN  1631026755142  1631030400000  1h0m44.858s   36556        483          483          86863
01FF0TGGE3KZ9Z81WP6B3RK1NS  1631030409766  1631037600000  1h59m50.234s  169533       483          483          171731
```

A workaround in the meantime for the overlapping issue, is to allow compaction to hit. I think that should resolve the problem, however compaction shouldn't be needed in the first place.

**Comment by codesome** [comment]
Is this fixed in https://github.com/prometheus/prometheus/pull/9324?

**Comment by jtougas** [comment]
> A workaround in the meantime for the overlapping issue, is to allow compaction to hit. I think that should resolve the problem, however compaction shouldn't be needed in the first place.

I believe I left it running long enough for compaction to occur, as well as restarting prometheus which I believe performs a compaction at startup, but it did not fix this.

Is there a way to force compaction to occur to verify this?

**Comment by roidelapluie** [comment]
Hello,

We have fixed this bug in Prometheus v2.30. You would need to run promtool again I believe.

**Comment by roidelapluie** [comment]
> > A workaround in the meantime for the overlapping issue, is to allow compaction to hit. I think that should resolve the problem, however compaction shouldn't be needed in the first place.
> 
> I believe I left it running long enough for compaction to occur, as well as restarting prometheus which I believe performs a compaction at startup, but it did not fix this.
> 
> Is there a way to force compaction to occur to verify this?

Can you please tell us if compaction runs at all? e.g. what are your prometheus parameters?

**Comment by jtougas** [comment]
2.30.0 seems to fix the issue indeed. I see this in the promtool output though once per rule:

```
rule importer error: query range: bad_data: invalid parameter "end": end timestamp must not be before start time
```

yet the data it creates seems good

**Comment by JessicaGreben** [comment]
@jtougas thanks for confirming the fix worked for you, although that log error was not expected. i will try to fix that.

**Comment by roidelapluie** [comment]
The fix for the error is at #9340 .
